### ISSUE TITLE
请问，您是如何使用这个插件的？

### ISSUE THREAD

**Issue by HowGraceU** [wuomzfx/hoox#3]
在公众号看到这个插件，有一个疑问，想请教一下。

如果项目已经使用 typescript，那么是直接引用 src 里的文件吗？
如果项目没有使用 typescript，是引用打包之后的文件吗？

想请教一下，您这边是如何在项目中使用的。
能否做到像 react 一样，生成 *.d.ts，让没有使用 typescript 的项目也可以享用类型提示。

**Comment by wuomzfx** [comment]
可以的，我忘记packge.json 里加types目录了，马上加一下~

**Comment by wuomzfx** [comment]
ok啦，0.2.3版本，ts 跟 js项目 都直接 import 即可。没有使用 typescript 的项目也可以享用类型提示。

**Comment by wuomzfx** [comment]
想用的话，可以加我微信多聊~ 75851654~
